name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests in Amazon Linux container
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace amazonlinux:2 bash -c "
            yum install -y python3.12 python3.12-pip &&
            pip3.12 install --upgrade pip &&
            pip3.12 install -r lambdas/requirements.test.txt &&
            cd lambdas && python3.12 -m pytest -sv
          "
