name: Python Lambda on Amazon Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Build custom Amazon Linux image
        run: |
          cp -f layers/requirements.txt .
          docker build -t custom-amazonlinux:2 -f .github/workflows/Dockerfile.github .
      - name: Run tests in custom Amazon Linux container
        run: |
          docker run --rm -v $(pwd)/lambdas:/workspace/lambdas -w /workspace/lambdas custom-amazonlinux:2 bash -c "
            pip3.12 install --upgrade pip &&
            pip3.12 install -r requirements.test.txt &&
            python3.12 -m pytest -sv
          "
